### ISSUE TITLE
Unfinished AngularJS code is shown while AngularJS is being loaded

### ISSUE THREAD

**Issue by AbdelRahmaneB** [hackergarten/hackergarten.github.io#103]
Unfinished AngularJS code is shown while AngularJS is being loaded:

![hackergarten](https://cloud.githubusercontent.com/assets/3718567/20159077/5cb6a168-a6d6-11e6-89d7-98b6cb61a8f4.png)

**Comment by madmas** [comment]
Never saw that before, but the fix looks fine, thanks a lot :)
