### ISSUE TITLE
Add projects section

### ISSUE THREAD

**Issue by AbdelRahmaneB** [hackergarten/hackergarten.github.io#107]
It would be nice to have a section that lists the projects that received the most contributions on hackergartens events.

**Comment by madmas** [comment]
That sound like a very nice idea, but it's hard to maintain / keep track of. And anything that requires more manual work will probably get lost ;-)

One thing that could work is to add an additional attribute "project" to the achievements. But then it starts: how do we avoid different spelling / typo problems, etc. (not to say that the achievements do not always the tracket even now that they are fairly light-weight (there has been a discussion to implement a frontend to make it easier to add them, though).

Did you already had an approach in mind how we could implement it, maybe an easier one? ;-)

**Comment by AbdelRahmaneB** [comment]
A frontend to crud events, projects, locations, achievements.. will be a good feature.
If we assume that all projects are on github (or other known repos), we can create a script to extract the projects from achievements, and count their occurrences and put that on a separate json file.
Or, like you suggested, the easiest way would be to add an additional attribute "project" to the achievements that will contain a reference to a project. Projects will be stored on a separate json file.

**Comment by McPringle** [comment]
We can do this automatically. Within the default gulp task we can parse the events JSON file, extract the achievements links and extract the project part from links to GitHub, Bitbucket etc.

Example: `https://github.com/hackergarten/hackergarten.github.io/issues/107`

Within GitHub links, the second path element is always the project: `hackergarten.github.io`

**Comment by madmas** [comment]
sounds good :-)

**Comment by McPringle** [comment]
@madmas Needs to be merged. Will create an Achievements-PR today with all Hackergarten Achievements from our Basel Meetup.
