### ISSUE TITLE
Canceled events should be shown in a special format

### ISSUE THREAD

**Issue by McPringle** [hackergarten/hackergarten.github.io#137]
Sometimes it happens that a previously announced meetup has to be canceled. just removing it from the `events.json` is one solution, but the event will be not listed anymore so visitors do not have the information, that the event was canceled. Adding the word `CANCELED` to the title and keep it listed is another solution. I would prefer a special state in the JSON file so a canceled event can be displayed in a different format using CSS, e.g. with a strike through and grayed out the title.

**Comment by aalmiray** [comment]
Also consider "re-escheduled" events.

**Comment by McPringle** [comment]
In work with PR #180
