### ISSUE TITLE
Add `hackergarten` label to all issues automatically

### ISSUE THREAD

**Issue by McPringle** [hackergarten/hackergarten.github.io#182]
The `hackergarten` label is used to determine all issues on GitHub, that can be done at a Hackergarten event. These issues are displayed on the [hackergarten website](http://hackergarten.net). In my opinion, all issues of the hackergarten website could be solved at a hackergarten.

**Comment by D4rkMindz** [comment]
Here an example to create a webhook:
https://developer.github.com/webhooks/creating/

How to use it on an issue
https://github.community/t5/How-to-use-Git-and-GitHub/Apply-labels-automatically-at-issue-creation/td-p/10719

**Comment by romixch** [comment]
We created a GitHub App which adds the label `hackergarten` to every new issue. The code is hosted on glitch:
https://glitch.com/edit/#!/tame-authorization

The app is available here on GitHub: https://github.com/apps/hackergarten-labeler
Once you add the app to your repository, any issue is marked `hackergarten`.

**Comment by McPringle** [comment]
@aalmiray @sclassen What do you think about adding the [hackergarten-labeler](https://github.com/apps/hackergarten-labeler) application to this repository?

**Comment by aalmiray** [comment]
It's been 4 years since this issue was created 😱 
Does the app still work? Any security issues we should take care of first?

**Comment by McPringle** [comment]
@aalmiray I don't see any issues. This is a GitHub action that is called on opening new issues and uses the GitHub REST API to set the `hackergarten` label on that issue. The action is based on the latest Ubuntu container, runs only for a few milliseconds, and does not consume any data (so no possibility to inject something).

@romixch, do you have to add something?

**Comment by aalmiray** [comment]
@scordio recently sent a PR to address this.

**Comment by scordio** [comment]
@McPringle are you referring to my PR (#366) or to [hackergarten-labeler](https://github.com/apps/hackergarten-labeler)?

I was looking at the hackergarten-labeler's [code](https://glitch.com/edit/#!/tame-authorization) and it doesn't appear to be based on GitHub Actions.

**Comment by McPringle** [comment]
@scordio I'm referring your PR. Sorry, I didn't mention it.
