### ISSUE TITLE
Remove obsolete branches

### ISSUE THREAD

**Issue by McPringle** [hackergarten/hackergarten.github.io#184]
It looks like these branches are leftover from merged pull requests:
- addKarakunAsHackergartenSponsor
- hackergarten-basel-june-2018
- hackergarten-bs-nov+dec2017
- madmas-fix-build

**Comment by McPringle** [comment]
This could be a task for @madmas at Hackergarten Basel today! :-)

**Comment by madmas** [comment]
Done :)
