### ISSUE TITLE
Calculate the number of the hack automatically

### ISSUE THREAD

**Issue by McPringle** [hackergarten/hackergarten.github.io#24]
Every hack is numbered. If you enter a new hack between two future hacks, you have to reorder the numbers manually. They can be calculated by the JavaScript dynamically, we don't need the hack number in the JSON file.

**Comment by aalmiray** [comment]
:+1: I suppose Angular can take care of this

**Comment by madmas** [comment]
improved during April Hackergarten Basel, thank you :+1:
