### ISSUE TITLE
The website shows the wrong event as next event.

### ISSUE THREAD

**Issue by McPringle** [hackergarten/hackergarten.github.io#33]
The event promoted as next event is on 7th June, but the next event is tomorrow (7th May)!
![bildschirmfoto 2015-05-06 um 16 06 54](https://cloud.githubusercontent.com/assets/1254039/7494791/18d95c68-f40a-11e4-9a3c-35d32cc24d03.png)

**Comment by McPringle** [comment]
This issue seems to be Chrome related!

**Comment by aalmiray** [comment]
Fixed along with https://github.com/hackergarten/hackergarten.github.io/pull/46
