### ISSUE TITLE
Add a Mastodon widget with recent messages

### ISSUE THREAD

**Issue by aalmiray** [hackergarten/hackergarten.github.io#359]

**Comment by McPringle** [comment]
Tip: Just about every profile page, hashtag page, or other content display page in Mastodon will automatically become an RSS feed if you tack `.rss` on the end of it.

Page: https://mastodon.social/tags/hackergarten
Feed: https://mastodon.social/tags/hackergarten.rss

**Comment by scordio** [comment]
```
curl https://fosstodon.org/api/v1/timelines/tag/hackergarten
```

seems to provide a good data source.

**Comment by McPringle** [comment]
We implemented this at Hackergarten Lucerne with PR https://github.com/hackergarten/hackergarten.github.io/pull/362
