### ISSUE TITLE
Twitter Section: #Hackergarten instead of @Hackergarten?

### ISSUE THREAD

**Issue by agitator** [hackergarten/hackergarten.github.io#395]
Hi all
I know Hackergarten moved to @hackergarten@fosstodon.org... but not everyone else ;-) 
Would it be an idea to change the Twitter(x-whatever) section to display tweets with hashtag #Hackergarten to make Hackergarten-SoMe-Activities a bit more visible on the site?
Cheers from Zurich
Peter

**Comment by madmas** [comment]
Hi @agitator , @scordio , 
would be fine for me, but as twitter now threatens to even introduce a paywall, I don?t want to spend time with it ;-)
As the box didn`t show anything, I removed it with https://github.com/hackergarten/hackergarten.github.io/pull/402

A new implementation showing the timeline for a hashtag from X would be welcome.

**Comment by McPringle** [comment]
There is no more Twitter/X on the website. This issue can be closed.
