### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by ollin** [hackergarten/hackergarten.github.io#43]
There is no licence declared. Can we use the logo/pictures for other hackergarten's (meetup etc.)?

**Comment by aalmiray** [comment]
It's a good thing you brought this issue forward. There will be a license for running Hackergarten events. Stay tuned.

**Comment by McPringle** [comment]
@aalmiray Do you have any news about this license topic?

**Comment by madmas** [comment]
There is a license declared on the homepage for some time now. Doesn't that fullfill this request?
