### ISSUE TITLE
Achievements - HTML not possible

### ISSUE THREAD

**Issue by PReimers** [hackergarten/hackergarten.github.io#47]
If using HTML in achievements-modal the HTML is displayed in plain text.

![hg_html_achievements](https://cloud.githubusercontent.com/assets/1785288/9489909/988c4a60-4be4-11e5-9b02-7cbb78daf74b.png)

**Comment by madmas** [comment]
Yes, I already notices that and gave some variants of "trustAsHtml" or ng-bind-html ng-bind-html-untrusted a shot, but without luck. @victorparmar, mybe you saw a possible solution to this while implementing the feature last night? :)

**Comment by victorparmar** [comment]
Hi - so I would say that allowing html as json text is leading us down a very slippery slope. Apart from that, I will need to look into it - I'm thinking maybe use jquery to just parse it and spit out the html to the modal. I'll get back to you on this!

**Comment by PReimers** [comment]
It's AngularJS witch parses the HTML as plain text.
I'm working on a solution, but it's not working as expected.

---

FYI:
__{{item}}__ is parsed as normal text
AngularJS has an attribute __ng-bind-html=""__witch allows parsing of html*

*) It's not working with __ng-repeat=""__

**Comment by victorparmar** [comment]
Ok so I was totally off track - @madmas had the right idea but was just missing a filter as provided here: http://stackoverflow.com/questions/19415394/with-ng-bind-html-unsafe-removed-how-do-i-inject-html/19417443#19417443. It's fixed now, I'll submit pull req :)

**Comment by PReimers** [comment]
@victorparmar how did you get the answer so fast?

I was working on it since 8-o-clock :(

**Comment by victorparmar** [comment]
@PReimers errrr I just googled it - I guess @madmas' suggestion put me on the right track :)
