### ISSUE TITLE
Fix 404 error for the background header image

### ISSUE THREAD

**Issue by victorparmar** [hackergarten/hackergarten.github.io#49]
The current implementation to randomly select the background image works but the browser initially tries to find an image for the function name provided. See screenshot: 
![image](https://cloud.githubusercontent.com/assets/1133427/9507363/fad57660-4c4d-11e5-9686-442291fc22b5.png)

**Comment by PReimers** [comment]
It's because the angular Framework is loaded at the bottom of the page.

1. Browser detects CSS
2. Browser detects HTML _<-- The error is here_
3. Browser detects Angular _<-- Here it's fixed_

**Comment by madmas** [comment]
I think it's not really worth to spend time with this; the user experience is not negatively affected, right?
