### ISSUE TITLE
Hackergarten in Beijing, China

### ISSUE THREAD

**Issue by paulvi** [hackergarten/hackergarten.github.io#5]
We have some meet-ups, and hackergarten is direction we actually should go.

I would not like to  copy ideas. But can I export brand, work as franchise, whatever suits your better.

The first step to try would be some event this month that will be announce on http://hackergarten.net/

This is not in hurry and is to be done when ready, possibly August and/or November

**Comment by madmas** [comment]
Hi @paulvi ,
it has been a while, any news from the Hackergarten Beijing?
I'd close the issue if there is o more feedback :)

**Comment by paulvi** [comment]
OK

Now I am in Shenzhen, China http://szjug.github.io/
