### ISSUE TITLE
Convert achievements content in a object like "links"

### ISSUE THREAD

**Issue by reinhapa** [hackergarten/hackergarten.github.io#84]
I would suggest to convert the existing json structure part of the achievements to a similar way as the links section:

From now:
```
 "achievements": [
      "Achievement without link",
      "<a href='http:/somehost.somedomain'>Awesome work</a>"
    ]
```

To something like this:
```
 "achievements": [
      {
        "title": "Achievement without link"
      },
      {
        "title": "Awesome work",
        "url": "http:/somehost.somedomain/"
      }
    ]
```

**Comment by madmas** [comment]
Hi, that idea looks really good to me. 
It would require to change the angular code and the json file (probably doable with a structural search/replace aka regexp, i think ;))
do you want to do a PR for this or work on one of the next hackergartens on it? :)

**Comment by reinhapa** [comment]
Just added PR #85 for this issue

**Comment by reinhapa** [comment]
Is there any Problem with my PR so far? I just did not see any comments so far...

**Comment by madmas** [comment]
Woha, I'm very sorry, it slipped through. I'll lokk at it first thing at the hackergarten tonight, thanks a lot!

**Comment by madmas** [comment]
as #85 got merged, I close this :)
thanks again for the PR!
