### ISSUE TITLE
title attribute in events.json should be "venue"

### ISSUE THREAD

**Issue by madmas** [hackergarten/hackergarten.github.io#88]
With the changes of #86 is seems to be obvious that the attribute title is not appropiate anymore, we should refactor that :)

**Comment by reinhapa** [comment]
As I designed the `events.json` format initially the fields where as follows:
`title` title or short description of the event
`location` where the event takes place, could contain venue or just city
`description` a long description about the general topics
`links`array to the sponsors containing `link` elements (details follow)
later there was added an `achievements` array, which I lately converted to `link` elements

A `link` element defines a simple link entry containing a `description`and a `url` value

When changing the `title` meaning to `venue` we should also migrate all existing entries accordingly.

**Comment by madmas** [comment]
ah, thanks for the outline! :)
yes, a migration would be required, I agree.
but i'd suppose thats anyway the case as currently, we misuse the title somewhat ;-)
I suggest: Either we use the title for actual title and change the current data and templates accordingly or we change the attribute name....

**Comment by reinhapa** [comment]
I would add a new `venue` field change the existing data accordingly. I started to write a simple JavaFX based editor in the past hackergarten for the events. That could be used to more simply edit the `events.json` file in the next event in Lucerne eventually...

**Comment by McPringle** [comment]
If we add the new `venue` field, what do we do with the `title` field? As I can see actually there is no need for a title, all entries in the `events.json` use the `title` field to specify the `venue` and all templates create the title by concatenating the fields. I suggest to simply refactor `title` to `venue` and add a `title` field when necessary.

I would really like to see the javaFX editor next Hackergarten in Lucerne… :-)

**Comment by madmas** [comment]
Well, the fact that all use the title field to mention the venue come from the way the file has been refactored. 
A title would be nice anyways, esp, for the non-standard events on conferences, etc.

**Comment by McPringle** [comment]
Ok, you are right. So let's use both fields: If no `title` is present a title will be generated using the other fields (like now).

**Comment by reinhapa** [comment]
Just for those of you that want to have a peek look into the current actual [event editor](https://github.com/reinhapa/eventeditor) state...
