### ISSUE TITLE
Allow HTTPS to access the hackergarten website

### ISSUE THREAD

**Issue by McPringle** [hackergarten/hackergarten.github.io#97]

**Comment by madmas** [comment]
You just need to accept that certificate ;-)

No, seriously, I did a little google on this:
* https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it
* https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/
* https://github.com/isaacs/github/issues/156

Unfortunately, what I understood, SSL is not fully supported for custom domains.
Also, as we do not have any login, SSL would be nice, but does not look crucial to me ;-)

**Comment by madmas** [comment]
This might bring some movement to this issue: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by McPringle** [comment]
That could be a topic for the May Hackergarten in Basel…

**Comment by madmas** [comment]
According to
* https://help.github.com/articles/securing-your-github-pages-site-with-https/
* https://help.github.com/articles/troubleshooting-custom-domains/#https-errors


we need to add an CAA DNS record entry: https://letsencrypt.org/docs/caa/

I'll see that I talk to the right people about that.

**Comment by sclassen** [comment]
+1

**Comment by McPringle** [comment]
Who has access to the DNS record of [hackergarten.net](http://hackergarten.net)?

**Comment by madmas** [comment]
Working on it, reached out to the Hackergarten initiator @HamletDRC  :)

**Comment by HamletDRC** [comment]
OK, I changed the nameservers to point at the Dotster name servers and then enabled the Free SSL. 
The nameservers had been dns1.canoo.ch and dns2.canoo.ch

I suspect that the website might be broken once the DNS records update 👍

**Comment by madmas** [comment]
@HamletDRC thanks a lot for looking into this :) 

I think according to https://help.github.com/articles/setting-up-an-apex-domain/ you need to setup a "A Record" to those IP adresses: 
```
    185.199.108.153
    185.199.109.153
    185.199.110.153
    185.199.111.153
```

HTTPS via the hoster will not work, but it can be provided from github, then: https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by HamletDRC** [comment]
I changed the nameservers to point back to Canoo to bring the website back. Please note that because of the way name servers work, it may take up to 24 hours for your changes to take effect. 
After the http domain is back then I'll update these A records.

**Comment by madmas** [comment]
@HamletDRC using you providers DNS is the way to go, as the A record would be created and served from there. Migrating away from Canoo's DNS is what we should do (see my email ;-) ).

**Comment by madmas** [comment]
At Hackergarten Basel July 2019 we actually had the chance to sit together and work on this. Should be solved as soon as DNS updates are through :)

**Comment by McPringle** [comment]
Works like a charm! Cool stuff!

**Comment by madmas** [comment]
Finally solved, yay :D 💃
